//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CoreAPI.Models.DataModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class AdminPanelConfig
    {
        public string F_UserID { get; set; }
        public Nullable<bool> FixedSidebar { get; set; }
        public Nullable<bool> SidebaronHover { get; set; }
        public Nullable<bool> SubmenuonHover { get; set; }
        public Nullable<bool> FixedTopbar { get; set; }
        public Nullable<bool> BoxedLayout { get; set; }
        public string Color { get; set; }
        public string Theme { get; set; }
        public string BackGround { get; set; }
        public string WebsiteTheme { get; set; }
        public string WebsiteThemeLangs { get; set; }
        public string WebSiteURL { get; set; }
    }
}
