//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CoreAPI.Models.DataModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class AttributeValue
    {
        public int ID { get; set; }
        public string Value { get; set; }
        public Nullable<int> F_AttributeID { get; set; }
        public Nullable<int> F_AttributeItemID { get; set; }
        public Nullable<int> F_ItemID { get; set; }
    
        public virtual Attribute Attribute { get; set; }
        public virtual AttributeItem AttributeItem { get; set; }
        public virtual Item Item { get; set; }
    }
}
