//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CoreAPI.Models.DataModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class ComponentItemSetUp
    {
        public int ID { get; set; }
        public Nullable<int> F_ComponentID { get; set; }
        public Nullable<int> F_ItemID { get; set; }
        public string Type { get; set; }
        public Nullable<double> Weight { get; set; }
    
        public virtual ComponentSetUp ComponentSetUp { get; set; }
    }
}
