//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CoreAPI.Models.DataModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class Languages
    {
        public string Language { get; set; }
        public string Image { get; set; }
        public Nullable<bool> isRTL { get; set; }
        public string LanguageName { get; set; }
        public Nullable<double> Weight { get; set; }
    }
}
