//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CoreAPI.Models.DataModel
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class Entities : DbContext
    {
        public Entities()
            : base("name=Entities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<AddressCity> AddressCity { get; set; }
        public virtual DbSet<AddressDistrict> AddressDistrict { get; set; }
        public virtual DbSet<AddressState> AddressState { get; set; }
        public virtual DbSet<AdminPanelConfig> AdminPanelConfig { get; set; }
        public virtual DbSet<Attribute> Attribute { get; set; }
        public virtual DbSet<AttributeGroup> AttributeGroup { get; set; }
        public virtual DbSet<AttributeItem> AttributeItem { get; set; }
        public virtual DbSet<AttributeValue> AttributeValue { get; set; }
        public virtual DbSet<Comments> Comments { get; set; }
        public virtual DbSet<ComponentItemSetUp> ComponentItemSetUp { get; set; }
        public virtual DbSet<ComponentSetUp> ComponentSetUp { get; set; }
        public virtual DbSet<Item> Item { get; set; }
        public virtual DbSet<ItemGallery> ItemGallery { get; set; }
        public virtual DbSet<Languages> Languages { get; set; }
        public virtual DbSet<Menu> Menu { get; set; }
        public virtual DbSet<PollAnswer> PollAnswer { get; set; }
        public virtual DbSet<PollLog> PollLog { get; set; }
        public virtual DbSet<PollQuestion> PollQuestion { get; set; }
        public virtual DbSet<Posts> Posts { get; set; }
        public virtual DbSet<Roll_Mapping_RollGroupe> Roll_Mapping_RollGroupe { get; set; }
        public virtual DbSet<RollGroupe> RollGroupe { get; set; }
        public virtual DbSet<Shekayat> Shekayat { get; set; }
        public virtual DbSet<ShekayatInboxOutBox> ShekayatInboxOutBox { get; set; }
        public virtual DbSet<Shop> Shop { get; set; }
        public virtual DbSet<ShopItem> ShopItem { get; set; }
        public virtual DbSet<Tags> Tags { get; set; }
        public virtual DbSet<Tags_Posts_Mapping> Tags_Posts_Mapping { get; set; }
        public virtual DbSet<Ticket> Ticket { get; set; }
        public virtual DbSet<TicketInbox> TicketInbox { get; set; }
        public virtual DbSet<TicketInboxMedia> TicketInboxMedia { get; set; }
        public virtual DbSet<TicketLog> TicketLog { get; set; }
        public virtual DbSet<TicketOutBox> TicketOutBox { get; set; }
        public virtual DbSet<UserInformation> UserInformation { get; set; }
        public virtual DbSet<UserRollMapping> UserRollMapping { get; set; }
        public virtual DbSet<AspNetRoles> AspNetRoles { get; set; }
        public virtual DbSet<AspNetUsers> AspNetUsers { get; set; }
    }
}
