//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CoreAPI.Models.DataModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class PollLog
    {
        public int ID { get; set; }
        public string IPAddress { get; set; }
        public string F_UserID { get; set; }
        public string Device { get; set; }
        public Nullable<System.DateTime> CreatedOnUTC { get; set; }
        public Nullable<int> F_PollAnswerID { get; set; }
    
        public virtual PollAnswer PollAnswer { get; set; }
    }
}
