//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CoreAPI.Models.DataModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class PollAnswer
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public PollAnswer()
        {
            this.PollLog = new HashSet<PollLog>();
        }
    
        public int ID { get; set; }
        public string Text { get; set; }
        public Nullable<int> AnswerKey { get; set; }
        public Nullable<int> Score { get; set; }
        public Nullable<int> F_PollQuestionID { get; set; }
        public string Color { get; set; }
    
        public virtual PollQuestion PollQuestion { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<PollLog> PollLog { get; set; }
    }
}
