//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CoreAPI.Models.DataModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class PollQuestion
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public PollQuestion()
        {
            this.PollAnswer = new HashSet<PollAnswer>();
        }
    
        public int ID { get; set; }
        public string Question { get; set; }
        public Nullable<System.DateTime> CreatedOnUTC { get; set; }
        public Nullable<System.DateTime> StartDateOnUTC { get; set; }
        public Nullable<System.DateTime> EndDateOnUTC { get; set; }
        public string F_UserID { get; set; }
        public Nullable<bool> isDeleted { get; set; }
        public string ChartType { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<PollAnswer> PollAnswer { get; set; }
    }
}
