//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CoreAPI.Models.DataModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class Posts
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Posts()
        {
            this.Comments = new HashSet<Comments>();
            this.Tags_Posts_Mapping = new HashSet<Tags_Posts_Mapping>();
        }
    
        public int ID { get; set; }
        public string Tittle { get; set; }
        public string Description { get; set; }
        public string Detail { get; set; }
        public string ImagePath { get; set; }
        public Nullable<bool> isDeleted { get; set; }
        public Nullable<bool> Status { get; set; }
        public string F_UserID { get; set; }
        public Nullable<int> F_MenuID { get; set; }
        public Nullable<int> NumberOfVisitors { get; set; }
        public Nullable<int> NumberOfComments { get; set; }
        public Nullable<int> NumberOfLikes { get; set; }
        public Nullable<int> NumberOfDislikes { get; set; }
        public Nullable<System.DateTime> CreatedOnUTC { get; set; }
        public string MetaDescription { get; set; }
        public string MetaTittle { get; set; }
        public string MetaSeoName { get; set; }
        public string ImageAlt { get; set; }
        public Nullable<bool> AllowComment { get; set; }
        public string Language { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Comments> Comments { get; set; }
        public virtual Menu Menu { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Tags_Posts_Mapping> Tags_Posts_Mapping { get; set; }
    }
}
