//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CoreAPI.Models.DataModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class Shop
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Shop()
        {
            this.ShopItem = new HashSet<ShopItem>();
        }
    
        public int ID { get; set; }
        public string F_UserID { get; set; }
        public string TotalPrice { get; set; }
        public string State { get; set; }
        public Nullable<System.DateTime> CreatedDateOnUtc { get; set; }
        public Nullable<bool> Payed { get; set; }
        public string PayType { get; set; }
        public string DeliveryType { get; set; }
        public string DeliveryCost { get; set; }
        public Nullable<System.DateTime> DeliveryTime { get; set; }
        public Nullable<System.DateTime> OrderedDate { get; set; }
        public string TransactionNumber { get; set; }
        public string ParentUserID { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ShopItem> ShopItem { get; set; }
    }
}
