//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CoreAPI.Models.DataModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class ShopItem
    {
        public int ID { get; set; }
        public Nullable<int> F_ItemID { get; set; }
        public Nullable<int> F_ShopID { get; set; }
        public Nullable<int> Count { get; set; }
        public Nullable<System.DateTime> CreatedDateOnUtc { get; set; }
    
        public virtual Item Item { get; set; }
        public virtual Shop Shop { get; set; }
    }
}
