//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CoreAPI.Models.DataModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class Tags_Posts_Mapping
    {
        public int ID { get; set; }
        public int F_TagsID { get; set; }
        public int F_PostsID { get; set; }
    
        public virtual Posts Posts { get; set; }
        public virtual Tags Tags { get; set; }
    }
}
