//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CoreAPI.Models.DataModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class TicketInboxMedia
    {
        public int ID { get; set; }
        public string MediaPath { get; set; }
        public string MediaType { get; set; }
        public Nullable<int> F_TicketInboxID { get; set; }
    
        public virtual TicketInbox TicketInbox { get; set; }
    }
}
