//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CoreAPI.Models.DataModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class TicketInbox
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public TicketInbox()
        {
            this.TicketInboxMedia = new HashSet<TicketInboxMedia>();
            this.TicketLog = new HashSet<TicketLog>();
            this.TicketOutBox = new HashSet<TicketOutBox>();
        }
    
        public int ID { get; set; }
        public string TicketContent { get; set; }
        public Nullable<System.DateTime> CreatedOnUTC { get; set; }
        public string TicketType { get; set; }
        public string TicketFrom { get; set; }
        public Nullable<int> F_TicketID { get; set; }
    
        public virtual Ticket Ticket { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TicketInboxMedia> TicketInboxMedia { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TicketLog> TicketLog { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TicketOutBox> TicketOutBox { get; set; }
    }
}
